#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ENV_FILE:-$ROOT_DIR/.env}"
REPO="${GITHUB_REPO:-sidosera/lolabunny.app}"

IDENTITY="${CODESIGN_IDENTITY:-}"
TEAM_ID="${APPLE_TEAM_ID:-}"
APPLE_ID="${APPLE_ID:-}"
APPLE_ID_PWD="${APPLE_ID_PWD:-}"
PUSH_SECRETS=0

usage() {
    cat <<'EOF'
Usage: scripts/create-signing-env.sh [options]

Exports the local Apple codesigning identity to a PKCS12, then writes
a gitignored .env with CI signing secrets.

Options:
  --identity NAME     Codesign identity (default: first Apple Development /
                      Developer ID Application from the keychain)
  --team-id ID        Apple team ID (default: parsed from the certificate)
  --apple-id EMAIL    Apple ID for notarization (optional)
  --apple-id-pwd PWD  App-specific password for notarization (optional)
  --env-file PATH     Output path (default: ./.env)
  --push              Also run: gh secret set -f <env-file> --repo <repo>
  --repo OWNER/NAME   GitHub repo for --push (default: sidosera/lolabunny.app)
  -h, --help          Show this help
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --identity)
            IDENTITY="${2:?}"
            shift 2
            ;;
        --team-id)
            TEAM_ID="${2:?}"
            shift 2
            ;;
        --apple-id)
            APPLE_ID="${2:?}"
            shift 2
            ;;
        --apple-id-pwd)
            APPLE_ID_PWD="${2:?}"
            shift 2
            ;;
        --env-file)
            ENV_FILE="${2:?}"
            shift 2
            ;;
        --push)
            PUSH_SECRETS=1
            shift
            ;;
        --repo)
            REPO="${2:?}"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "unknown option: $1" >&2
            usage >&2
            exit 1
            ;;
    esac
done

resolve_identity() {
    if [[ -n "$IDENTITY" ]]; then
        printf '%s\n' "$IDENTITY"
        return
    fi

    local found=""
    found="$(security find-identity -v -p codesigning 2>/dev/null \
        | sed -n 's/.*"\(Developer ID Application: .*\)"/\1/p' \
        | head -n 1)"
    if [[ -z "$found" ]]; then
        found="$(security find-identity -v -p codesigning 2>/dev/null \
            | sed -n 's/.*"\(Apple Development: .*\)"/\1/p' \
            | head -n 1)"
    fi
    if [[ -z "$found" ]]; then
        echo "No usable codesigning identity found." >&2
        echo "Run: security find-identity -v -p codesigning" >&2
        exit 1
    fi
    printf '%s\n' "$found"
}

resolve_team_id() {
    if [[ -n "$TEAM_ID" ]]; then
        printf '%s\n' "$TEAM_ID"
        return
    fi

    local subject=""
    subject="$(security find-certificate -c "$IDENTITY" -p 2>/dev/null \
        | openssl x509 -noout -subject 2>/dev/null || true)"
    # subject= .../OU=TEAMID/...
    local team=""
    team="$(printf '%s\n' "$subject" | sed -n 's/.*OU=\([^/]*\).*/\1/p' | head -n 1)"
    if [[ -z "$team" ]]; then
        echo "Could not parse APPLE_TEAM_ID from certificate; pass --team-id." >&2
        exit 1
    fi
    printf '%s\n' "$team"
}

IDENTITY="$(resolve_identity)"
TEAM_ID="$(resolve_team_id)"

TMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/lolabunny-signing.XXXXXX")"
cleanup() {
    rm -rf "$TMP_DIR"
}
trap cleanup EXIT

P12="$TMP_DIR/identity.p12"
P12_PWD="$(openssl rand -base64 32 | tr -d '/+=' | head -c 32)"

echo "Exporting identity: $IDENTITY"
echo "Keychain Access may prompt to allow exporting the private key."
security export \
    -k "$HOME/Library/Keychains/login.keychain-db" \
    -t identities \
    -f pkcs12 \
    -o "$P12" \
    -P "$P12_PWD"

# Prefer exporting only the chosen identity when possible by re-packaging
# from the cert+key if the dump contains multiple identities.
CERT_B64="$(base64 < "$P12" | tr -d '\n')"

umask 077
cat > "$ENV_FILE" <<EOF
# Generated by scripts/create-signing-env.sh — do not commit
# Push: gh secret set -f $(basename "$ENV_FILE") --repo $REPO

CODESIGN_IDENTITY=$IDENTITY
APPLE_TEAM_ID=$TEAM_ID
MACOS_CERTIFICATE=$CERT_B64
MACOS_CERTIFICATE_PWD=$P12_PWD
APPLE_ID=$APPLE_ID
APPLE_ID_PWD=$APPLE_ID_PWD
EOF

echo "Wrote $ENV_FILE"
echo "  CODESIGN_IDENTITY=$IDENTITY"
echo "  APPLE_TEAM_ID=$TEAM_ID"
echo "  MACOS_CERTIFICATE=[${#CERT_B64} chars]"
echo "  MACOS_CERTIFICATE_PWD=[set]"
echo "  APPLE_ID=${APPLE_ID:-"[empty]"}"
echo "  APPLE_ID_PWD=${APPLE_ID_PWD:+[set]}${APPLE_ID_PWD:-[empty]}"

if [[ "$PUSH_SECRETS" -eq 1 ]]; then
    if ! command -v gh >/dev/null 2>&1; then
        echo "gh CLI not found; skip --push" >&2
        exit 1
    fi
    echo "Pushing secrets to $REPO ..."
    gh secret set -f "$ENV_FILE" --repo "$REPO"
    echo "Done."
fi
